# /Gemfile

source "https://rubygems.org"

gem "activesupport"
gem "awesome_print"
gem "pry-byebug"
gem "http"
gem "dotenv"
gem "json"
gem "daru"
gem "ascii_charts"
gem "openai"
gem "ruby-openai"
gem "sinatra"
gem "puma"
gem "rackup"
gem "sinatra-contrib"
gem "better_errors"
gem "binding_of_caller"
